layout_spectrum: 1
typography_spectrum: 0.2025794
color:
  saturation: 0.01337224
  brandStrength: 0.8531859
  lightness: 0.01402031
  brandColors:
    - '#E0E0E0'
    - '#202020'
    - '#9A9A9A'
  rhythmicContrast: 0.7265679
name: claudiayahany
